name: "Bidding on Rarible"
on:
  # schedule:
  # - cron: "*/30 * * * *""
  workflow_dispatch: {}

jobs:
  actions:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install pip
        run: |
          python -m ensurepip --upgrade
      
      - name: Install dependencies with pip
        run: |
          pip install -r requirements.txt
          
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          
      - name: Install dependencies with npm
        run: npm install
      
      - name: Create orders
        env:
            ADDRESS: ${{ secrets.ADDRESS }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            API_KEY: ${{ secrets.API_KEY }}
        run: |
          python3 main.py
          echo "## Sending orders" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

